# Generated by Django 4.2.5 on 2023-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('habitat', models.CharField(max_length=200)),
                ('conservation_status', models.CharField(max_length=200)),
                ('population', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
